version: '3'

services:
  agent-pepe:
    container_name: agent-pepe
    build:
      dockerfile: Dockerfile
    pull_policy: build
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: 10.10.2.37

networks:
  lan:
    name: LAN
    external: true
