version: '3'

services:
  agent-pepe:
    container_name: agent-pepe
    build:
      dockerfile: Dockerfile
    pull_policy: build
    networks:
      - mariadb
    env_file:
      - stack.env
    restart: unless-stopped

networks:
  mariadb:
    name: MariaDB
    external: true